//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter5.MonoAndroidApp
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Add = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int Contents = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int Delete = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int Notes = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int Save = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int Title = 2131099648;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNote = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NoteListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Notes = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewNote = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int Notes = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ViewNote = 2131034113;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
